#!/usr/bin/env python3
"""
Intel HEX to C Header Converter for Arduino-Forth project.
Converts Intel HEX format to C/C++ header file with PROGMEM byte array.

This replaces the gforth-based conversion script.

Author: Open Source Replacement
License: Public Domain (matching FIG-FORTH release)
"""

import sys
from typing import List, Tuple

def parse_intel_hex(filename: str) -> bytearray:
    """Parse Intel HEX file and return binary data"""
    data = bytearray(0x4000)  # 16KB
    
    with open(filename, 'r') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line or not line.startswith(':'):
                continue
            
            # Parse record
            try:
                byte_count = int(line[1:3], 16)
                address = int(line[3:7], 16)
                record_type = int(line[7:9], 16)
                
                if record_type == 0:  # Data record
                    for i in range(byte_count):
                        byte_val = int(line[9 + i*2:11 + i*2], 16)
                        data[address + i] = byte_val
                elif record_type == 1:  # EOF record
                    break
                    
            except Exception as e:
                print(f"Error parsing line {line_num}: {e}", file=sys.stderr)
                continue
    
    return data

def generate_c_header(data: bytearray, output_file: str, array_name: str = "body", array_size: int = 0x4000):
    """Generate C header file with PROGMEM byte array"""
    
    with open(output_file, 'w') as f:
        # Write header
        f.write("/*\n")
        f.write(" * ArdufigoROM.h - Auto-generated ROM image for Arduino-Forth\n")
        f.write(" * \n")
        f.write(" * This file contains the outer interpreter compiled from Ardufigo.ASM\n")
        f.write(" * Generated by hex2header.py - Open Source TASM replacement\n")
        f.write(" * \n")
        f.write(" * FIG-FORTH is PUBLIC DOMAIN\n")
        f.write(" * This publication has been made available by the\n")
        f.write(" *   Forth Interest Group\n")
        f.write(" *   P.O.Box 1105\n")
        f.write(" *   San Carlos, CA 94070\n")
        f.write(" *   U.S.A.\n")
        f.write(" */\n\n")
        
        # Write array declaration
        f.write(f"const PROGMEM byte {array_name}[0x{array_size:04X}] = {{\n")
        
        # Write data in rows of 16 bytes with ASCII representation
        for addr in range(0, array_size, 16):
            # Get 16 bytes
            row_data = data[addr:addr+16]
            
            # Write hex values
            f.write("0x{:02X}".format(row_data[0]))
            for byte in row_data[1:]:
                f.write(", 0x{:02X}".format(byte))
            
            # Write ASCII representation as comment
            ascii_repr = ""
            for byte in row_data:
                if 32 <= byte <= 126:
                    ascii_repr += chr(byte)
                else:
                    ascii_repr += "."
            
            f.write(f", // {ascii_repr} {addr:04X}\n")
        
        # Close array
        f.write("};\n")

def main():
    if len(sys.argv) < 3:
        print("Usage: hex2header.py <input.hex> <output.h> [array_name] [array_size_hex]")
        print("Example: hex2header.py Ardufigo.hex ArdufigoROM.h body 0x4000")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    array_name = sys.argv[3] if len(sys.argv) > 3 else "body"
    array_size = int(sys.argv[4], 16) if len(sys.argv) > 4 else 0x4000
    
    # Parse Intel HEX
    print(f"Parsing {input_file}...")
    data = parse_intel_hex(input_file)
    
    # Generate C header
    print(f"Generating {output_file}...")
    generate_c_header(data, output_file, array_name, array_size)
    
    print("Conversion complete!")

if __name__ == "__main__":
    main()
